"""
Cryptographic Audit Chain Verification Service for BankVCS 2.0.

Provides pure Python helper functions for audit trail integrity verification,
genesis block validation, hash chain repair checks, and security event correlation.
"""

import hashlib
import json
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional, Tuple

from app import db
from app.models.audit_log import AuditLog, AuditAction
from app.models.user import User

logger = logging.getLogger(__name__)


class AuditChainService:
    """
    High-level service for inspecting, validating, and reporting on the cryptographic
    integrity of the system's SHA-256 audit log blockchain.
    """

    @classmethod
    def verify_full_chain_integrity(cls) -> Dict[str, Any]:
        """
        Traverses every AuditLog entry from genesis (id=1) to the latest entry.
        Verifies that:
        1. prev_hash matches the previous record's current_hash.
        2. current_hash matches the re-computed SHA-256 hash of payload + prev_hash.
        """
        logs = AuditLog.query.order_by(AuditLog.id.asc()).all()
        if not logs:
            return {
                "status": "EMPTY",
                "is_intact": True,
                "total_records": 0,
                "verified_records": 0,
                "broken_records": [],
                "tampered_logs": [],
                "genesis_hash": None,
                "head_hash": None,
            }

        broken_records = []
        tampered_logs = []
        expected_prev_hash = logs[0].previous_hash if logs else "GENESIS"

        for index, log in enumerate(logs):
            # Check 1: Chain continuity
            if log.previous_hash != expected_prev_hash:
                broken_records.append({
                    "id": log.id,
                    "action": log.action,
                    "expected_prev_hash": expected_prev_hash,
                    "actual_prev_hash": log.previous_hash,
                    "timestamp": log.created_at.isoformat() if log.created_at else None,
                })

            # Check 2: Payload integrity
            computed_hash = log.calculate_hash()
            if log.current_hash != computed_hash:
                tampered_logs.append({
                    "id": log.id,
                    "action": log.action,
                    "stored_hash": log.current_hash,
                    "computed_hash": computed_hash,
                    "timestamp": log.created_at.isoformat() if log.created_at else None,
                })

            expected_prev_hash = log.current_hash

        is_intact = (len(broken_records) == 0) and (len(tampered_logs) == 0)

        return {
            "status": "VALID" if is_intact else "CORRUPTED",
            "is_intact": is_intact,
            "total_records": len(logs),
            "verified_records": len(logs) - len(broken_records) - len(tampered_logs),
            "broken_records": broken_records,
            "tampered_logs": tampered_logs,
            "genesis_hash": logs[0].current_hash if logs else None,
            "head_hash": logs[-1].current_hash if logs else None,
        }

    @classmethod
    def get_action_breakdown(cls) -> Dict[str, int]:
        """Calculates frequency count of audit actions across the entire audit ledger."""
        counts = {}
        logs = AuditLog.query.all()
        for log in logs:
            action_str = log.action or "UNKNOWN"
            counts[action_str] = counts.get(action_str, 0) + 1
        return counts

    @classmethod
    def get_user_activity_summary(cls, user_id: int) -> Dict[str, Any]:
        """Summarizes all audit logs generated by a specific user."""
        user = db.session.get(User, user_id)
        if not user:
            return {"user_id": user_id, "found": False}

        logs = AuditLog.query.filter_by(user_id=user_id).order_by(AuditLog.created_at.desc()).all()
        
        actions_list = [log.action for log in logs]
        return {
            "user_id": user.id,
            "found": True,
            "username": user.username,
            "user_role": str(user.role),
            "total_audit_events": len(logs),
            "recent_events": [log.to_dict() for log in logs[:10]],
            "actions_summary": {act: actions_list.count(act) for act in set(actions_list)},
        }

    @classmethod
    def export_audit_summary_json(cls) -> str:
        """Generates JSON formatted audit report with chain status and action breakdown."""
        chain_status = cls.verify_full_chain_integrity()
        action_breakdown = cls.get_action_breakdown()
        
        payload = {
            "audit_chain_verification": chain_status,
            "action_frequency_breakdown": action_breakdown,
            "exported_at": datetime.utcnow().isoformat() + "Z",
            "system_identifier": "BANKVCS_2_0_AUDIT_LEDGER",
        }
        return json.dumps(payload, indent=2)
