"""initial_schema_v2

Revision ID: 9a6219d6b469
Revises: 
Create Date: 2026-09-13 13:07:26.446204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6219d6b469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fraud_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_foreign_key(None, 'security_incidents', ['incident_id'], ['id'])

    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_up_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('step_up_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_login_sessions_step_up_token'), ['step_up_token'], unique=True)

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_taken', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('anomaly_details', sa.JSON(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_idempotency_key'), ['idempotency_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_column('anomaly_details')
        batch_op.drop_column('action_taken')

    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_step_up_token'))
        batch_op.drop_column('step_up_expires_at')
        batch_op.drop_column('step_up_token')

    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_incident_id'))
        batch_op.drop_column('incident_id')

    # ### end Alembic commands ###
